"""changes models relationship

Revision ID: 831681e60a76
Revises: a57256c5bf78
Create Date: 2024-10-12 11:48:53.688784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '831681e60a76'
down_revision = 'a57256c5bf78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
